const tintColor = '#21ACA5';

export default {
  teal: '#21ACA5',
  tintColor,
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
  // To Do: remove above colors and dependencies
  lightPurple: '#9E90A2',
  coral: '#E3655B',
  mustard: '#E3B23C',
  wine: '#A4243B',
  pink: '#EA638C',
  nightSky: '#495867',
  lightBlue: '#8EB8E5',
  orange: '#EA8C55',
  peach: '#FFB997',
  darkBlue: '#28536B',
  purple: '#8783D1',
  mauve: '#BD9391',
  merlot: '#8B1E3F',
  blue: '#357DED',
  green: '#9DBF9E',
};
